### ISSUE TITLE
Bluescreen

### ISSUE THREAD

**Issue by hideways** [kenn-notation/Guarded-Regions-Bypass-Valorant#4]
Giving bluescreen with the new driver (feature added move_mouse).

Win 10 version 20H2

**Comment by josealissonbr** [comment]
here too

**Comment by WafflesGaming** [comment]
yeah it broke with the update use this link to get the old version, i compiles and works fine
https://github.com/Chase1803/UCMiraka-ValorantExternal/tree/3946ab09a167e4503af483a301b6f8975fcad368/Kernel
